# Generated by Django 5.1 on 2024-12-14 14:47

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdTime',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_numeric',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=base.models.current_time_gmt2),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='availability',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='date_recorded',
            field=models.DateTimeField(default=base.models.current_time_gmt2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='created_at',
            field=models.DateTimeField(default=base.models.current_time_gmt2),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='availability',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='date_scraped',
            field=models.DateTimeField(default=base.models.current_time_gmt2),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='created_at',
            field=models.DateTimeField(default=base.models.current_time_gmt2),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateTimeField(default=base.models.current_time_gmt2),
        ),
    ]
